# Auto-generated by BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/projects/svdc/P4wsIPCSW/buildsw_storm_1_13/storm/storm_1_13/tianocore
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/projects/svdc/P4wsIPCSW/buildsw_storm_1_13/storm/storm_1_13/tianocore/BaseTools
fi
if [ -e /projects/svdc/P4wsIPCSW/buildsw_storm_1_13/storm/storm_1_13/tianocore/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//projects/svdc/P4wsIPCSW/buildsw_storm_1_13/storm/storm_1_13/tianocore/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/projects/svdc/P4wsIPCSW/buildsw_storm_1_13/storm/storm_1_13/tianocore/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
